# Generated by Django 4.2 on 2024-01-05 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perwakin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.region')),
            ],
            options={
                'verbose_name_plural': 'Perwakins',
            },
        ),
    ]
