# Generated by Django 4.2 on 2024-01-05 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_bidang_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='IsImportant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Is importants',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.bidang')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.country')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.gender')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.group')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.hobby')),
                ('is_important', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.isimportant')),
                ('perwakin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.perwakin')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.profession')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.region')),
            ],
            options={
                'verbose_name_plural': 'Professions',
            },
        ),
    ]
