# Generated by Django 4.2 on 2024-01-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_gender_hobby_isimportant_profession_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='hobby',
        ),
        migrations.AddField(
            model_name='contact',
            name='hobby',
            field=models.ManyToManyField(to='contact.hobby'),
        ),
    ]
