# Generated by Django 4.2 on 2024-01-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contact_options_remove_contact_hobby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profession',
        ),
        migrations.AddField(
            model_name='contact',
            name='profession',
            field=models.ManyToManyField(to='contact.profession'),
        ),
    ]
