# Generated by Django 4.2 on 2024-01-05 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_remove_contact_profession_contact_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Interests',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='interest',
            field=models.ManyToManyField(to='contact.interest'),
        ),
    ]
