# Generated by Django 4.2 on 2024-01-05 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_interest_contact_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Salutations',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='salutation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contact.salutation'),
            preserve_default=False,
        ),
    ]
