# Generated by Django 4.2 on 2024-01-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_salutation_contact_salutation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='group',
        ),
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ManyToManyField(to='contact.group'),
        ),
    ]
